name: Continuous Integration
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Unit tests
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        qt-version: [5, 6]
        qt-binding: [pyqt, pyside]
        exclude:
          - python-version: '3.10'
            qt-version: 5
            qt-binding: pyside
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('test_requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade --upgrade-strategy eager pip wheel
      - name: Install project and testing dependencies with [user]
        # Use installed version when moving to a source directory structure
        run: |
          pip install --upgrade --upgrade-strategy eager .[qt${{ matrix.qt-version }}-${{ matrix.qt-binding }}] -r test_requirements.txt
      - name: Test with pytest
        run: |
          pytest tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
