name: Lint sources
on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - "gild/**"
      - "tests/**"
      - pyproject.toml

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('lint_requirements.txt') }}
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r lint_requirements.txt
      - name: Install project (to get dependencies)
        run: |
          pip install .[qt6-pyqt]
      - name: Isort
        run: |
          isort . -c;
      - name: Black
        if: always()
        run: |
          black . --check;
      - name: Flake8
        if: always()
        run: |
          flake8 src;
      # - name: Mypy
      #   if: always()
      #   run: |
      #     mypy src;
